# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 01 - GoodAsOldPhones' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 01 - GoodAsOldPhones
pod 'SnapKit'

end
